### ISSUE TITLE
Getting FINGER_USB_PERMISSION_ERROR for ZK9500 device 

### ISSUE THREAD

**Issue by chorauoc** [amorenew/flutter_zkteco_fingerprint#1]
Hello,

I am tying to connect **ZK9500** device via USB to the mobile ,but i am getting these errors

01. When i pressed the button to check if the device is support or not then it show **false** . I would like to know why this is happening, because i am using latest 9500 version device? Is any **pre configurations** need to be made? And what is the **Registration Code** means ? 

02. When i press open connection, it always return **true**, but when i pressed start listing, then i am getting **FINGER_USB_PERMISSION_ERROR**. So i would be really great full to you if you can help me on this

And is there any **sequence** of those button to be pressed in the example app, can you provide me small guide to how to connect my device and start registering and very fingers.

I know these are some amount of question form my side, but if you can help me to resolve these question then i would e really great full to you

Thank you
Asanka

**Comment by amreniouinnovent** [comment]
@chorauoc 
1-the device is supported ignore it.. it was for checking my tablet model not needed
2-FINGER_USB_PERMISSION_ERROR
My Fingerprint is connected to the tablet by a USB hardware 
So I have in my Android Manifest this permission:
`    <uses-permission android:name="android.hardware.usb.host" />
`
3-Sequence could be Open then Start then Enroll

**Comment by chorauoc** [comment]
@amreniouinnovent 

Thanks for your reply, please note i didn't changed anything from your github repo, just open example app in vscode and run it, so are you asking from me to remove that  android.hardware.usb.host permission or something else ? . Because i am also running this app in a tablet which is running Andoid 6.0.1 version, is this version might be the issue? Because it did not asked any permissions to allow 

Thank you
Asanka

**Comment by amreniouinnovent** [comment]
@chorauoc 
Actually I don't know my finger hardware model so maybe there is a different SDK for your device model.
You could use this implementation as a guide if you want to make your own plugin for your finger model ZK9500.

**Comment by chorauoc** [comment]
Hello,
Thank you very much for your time

Thanks
Asanka

**Comment by chorauoc** [comment]
Hello,

Sorry for again, bt i have found that this permission error is happening due to PID mismatch, can you tell me how to get this PID for ZK9500 model

<usb-device vendor-id="6997" product-id="**289**" />

**Comment by amreniouinnovent** [comment]
@chorauoc 
very good you catch the issue
I think it is related to the model itself
```
    private static final int VID = 6997; // Silkid VID always 6997
    private static final int PID = 289; // Silkid PID always 289

```
Do you a native SDK for this model?
If not I suggest you ask on the ZKTeco support

> We provide SDKs for customers to develop their own applications.
support link
http://v3.faqrobot.org/robot/faqrobotEn.html?sysNum=14370257485604393


>

**Comment by chorauoc** [comment]
Hello,

Again thanks for the reply, I manged to get the PID and VID using another plugin called **usb serial** and found out that those are 👍 **VID 699**7 and **PID 292**, and i have changed those in your xml file also, but not working, same error appears.

And i will try to contact the support center for this ZK9500 model , i think this is due to this model, and one thing **what is the model that you use, so if your model is working then i would consider to buy that one because it is working for your plugin right ?**

And update your model details in the plugin description it self , so any other person might get benefit of your work 

Thanks you
Asanka

**Comment by amreniouinnovent** [comment]
@chorauoc I don't know the model number as a Chinese company made an embedded fingerprint module in a custom tablet
Once the support reply to you ask them for a native SDK then everything will be fine as you can make a flutter plugin in 2 working days or less

**Comment by chorauoc** [comment]
Hi,

After few days ZK Teco has replied that don't have native SDK for specific version , instead of that they said that they used your sdk for all the versions, so i deep dive into you app and found out that yo have hard coded the PID in two places in your lib as **292**, so i changed all the places into my PID of **296**, after that i manged to get the USB permissions but now when i clicked Start Listing is is showing "**FingerStatusType STARTED_ERROR**" ms, since this is comes form your custom enum, i wold like to know if you can help me on this 

Thank you

**Comment by amreniouinnovent** [comment]
@chorauoc What are the exception details?
It should be printed in your console

```
mFingerListener.onStatusChange(
"begin capture fail errno=" + e.getErrorCode() + 
",Internal error code: "   + e.getInternalErrorCode() + 
",message=" + e.getMessage(),
 FingerStatusType.STARTED_ERROR, "", "");

```

**Comment by chorauoc** [comment]
hello,

Can you tell me a way to obtain these logs, because i cant use Flutter usb debug and ZK9500 device in same tab at the same time, so if i use the device then i can't debug, so that is why i asked help form you ? Do you know any other way to get that logs

**Comment by chorauoc** [comment]
Hello,

I managed to connect the mobile via Wify and obtained these logs form the console, please check and let me know why this error comming 

D/ViewRootImpl@74b15d0[MainActivity](10975): ViewPostIme pointer 0
D/ViewRootImpl@74b15d0[MainActivity](10975): ViewPostIme pointer 1
D/Zkteco FingerPrint(10975): startFingerSensor
D/zkfinger(10975): user_limit = 0
I/flutter (10975): Instance of 'FingerStatus'
I/flutter (10975): FingerStatusType.STARTED_ERROR

**Comment by chorauoc** [comment]
Hello,
And i put manual debug msg and got full stack-trace when i pressed the Listing Button

D/ViewRootImpl@74b15d0[MainActivity](14458): ViewPostIme pointer 0
D/ViewRootImpl@74b15d0[MainActivity](14458): ViewPostIme pointer 1
D/Zkteco FingerPrint(14458): startFingerSensor
D/zkfinger(14458): [1]10 algorithm version:3.0
D/zkfinger(14458): user_limit = 30000
D/Zkteco FingerPrint(14458): came 03
W/System.err(14458): com.zkteco.android.biometric.module.fingerprint.exception.FingerprintSensorException: Cancel operation failed
W/System.err(14458): 	at com.zkteco.android.biometric.module.fingerprint.FingerprintSensor.setSysOption_imp(FingerprintSensor.java:426)
W/System.err(14458): 	at com.zkteco.android.biometric.module.fingerprint.FingerprintSensor.open(FingerprintSensor.java:166)
W/System.err(14458): 	at com.zkteco.zkfinger.ZKFingerPrintHelper.startFingerSensor(ZKFingerPrintHelper.java:310)
W/System.err(14458): 	at com.zkteco.zkfinger.ZkFingerPlugin.startFingerListen(ZkFingerPlugin.java:215)
W/System.err(14458): 	at com.zkteco.zkfinger.ZkFingerPlugin.onMethodCall(ZkFingerPlugin.java:166)
W/System.err(14458): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/System.err(14458): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/System.err(14458): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
W/System.err(14458): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(14458): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err(14458): 	at android.os.Looper.loop(Looper.java:181)
W/System.err(14458): 	at android.app.ActivityThread.main(ActivityThread.java:7076)
W/System.err(14458): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(14458): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(14458): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by amreniouinnovent** [comment]
@chorauoc Actually I don't know what could be the issue
do you have an XML file with device_filter.xml?
if it doesn't work maybe my SDK not compatible with your model

**Comment by amreniouinnovent** [comment]
try the native SDK without Flutter if you have it

**Comment by chorauoc** [comment]
Hello,

Here is that SDK, can you check what is wrong with this and your one https://drive.google.com/file/d/1t45KbPu4OZ0JKKAjMPRAES2aFNe2sul1/view?usp=sharing

**Comment by chorauoc** [comment]
Yes i have added my PID into device_filter.xml?

**Comment by amreniouinnovent** [comment]
@chorauoc Your SDK is different than my SDK
Check for example the c++ libraries it is different the .so files
So you need to make your own flutter plugin for your SDK

**Comment by chorauoc** [comment]
Hello,

Thank you very much for help me till here, ok i will try to make my own

**Comment by jamadorm** [comment]
Hi @chorauoc , I have the same problem as you. I am using Flutter, I changed the parameters of the VID and the PID and nothing. I added the permissions and it doesn't work. I run the app on my mobile device that supports OTG (Huawei Mate 20 Lite) and it marks the same mistakes. I also have a zkteco 9500 usb.
Have you been able to solve it?

**Comment by chorauoc** [comment]
@jamadorm 

I just used there native SDK in the above link and build that **sample native android project** ,which you can find in the folder itself, and it worked, but i have to did some modification in the code due to permission issue. But i did not able to achieve this using **this plugin**, so no way to use this in Flutter unless we develop our own plugin

**Comment by amreniouinnovent** [comment]
@chorauoc @jamadorm Maybe you could make a repo and do it together
I can't help because I don't have the same model
But you could use this plugin as a guideline
First, clean the native SDK into a single helper class like mine then it will be easy to do it fully

**Comment by sandypurnomo** [comment]
> Hello,
> 
> Here is that SDK, can you check what is wrong with this and your one https://drive.google.com/file/d/1t45KbPu4OZ0JKKAjMPRAES2aFNe2sul1/view?usp=sharing

Hi i`m also trying to make an android app wih zk9500. i tried your link but it seem the file no longer exist. could you give me new link for me ? I already tried many sdk from net but nothing work. sorry for bad english

**Comment by Mamasodikov** [comment]
Hi, I wrote a new plugin inspired by this plugin for the latest SDK (Live10R/ZK9500, Live20R, SLIKID).

https://github.com/Mamasodikov/zk_finger_10

**Comment by julioantonio12** [comment]
> Hi, I wrote a new plugin inspired by this plugin for the latest SDK (Live10R/ZK9500, Live20R, SLIKID).
> 
> https://github.com/Mamasodikov/zk_finger_10

Hello, Mamasodikov, I am so happy to find your zk_finger_10 flutter project. I sent you an email with a question I hope you can answer, it would be so valuable for me and my co-workers to implement a flutter app based on your project. Thank you so much for your time.

**Comment by Mamasodikov** [comment]
> > Hi, I wrote a new plugin inspired by this plugin for the latest SDK (Live10R/ZK9500, Live20R, SLIKID).
> > https://github.com/Mamasodikov/zk_finger_10
> 
> Hello, Mamasodikov, I am so happy to find your zk_finger_10 flutter project. I sent you an email with a question I hope you can answer, it would be so valuable for me and my co-workers to implement a flutter app based on your project. Thank you so much for your time.

Hi Julio Antonio, Thanks for your warm comments, I've just replied to your e-mail!

**Comment by Sirjiskit** [comment]
Hello @Mamasodikov  I used your new zk_finger_10 it works on debug but when I build the release it does not work. Can you please tell me what is the cause?

**Comment by julioantonio12** [comment]
@Sirjiskit  I don't understand the cause, but I fixed that issue adding these lines of code in your build.gradle file from android/app folder:
![image](https://github.com/amorenew/flutter_zkteco_fingerprint/assets/71475431/0181cdb9-1cf3-4484-95e9-9c49d50417ac)

**Comment by Mamasodikov** [comment]
> Hello @Mamasodikov I used your new zk_finger_10 it works on debug but when I build the release it does not work. Can you please tell me what is the cause?

Hi, I fixed issues and launched it to pub.dev: https://pub.dev/packages/zkfinger10
