### ISSUE TITLE
Migrate plugin to null safety!!

### ISSUE THREAD

**Issue by Mamasodikov** [amorenew/flutter_zkteco_fingerprint#5]

**Comment by amorenew** [comment]
@Mamasodikov I migrated it to null safety
https://pub.dev/packages/zk_finger/versions/2.0.1

**Comment by Mamasodikov** [comment]
> @Mamasodikov I migrated it to null safety https://pub.dev/packages/zk_finger/versions/2.0.1

Oh, thank you brother a lot! Appreciate your prompt response!
